window.ALEGI = {
  phoneDisplay: "+57 323 453 9556",
  phoneDigits: "573234539556",
  instagramUrl: "https://www.instagram.com/alegi2510?stkn=MXNmbGRnMm0weG5jNg==",
  instagramHandle: "@ALEGI2510",
  hours: "Lunes a Sábado · 9:00 AM – 7:00 PM",
  location: "Colombia · Envíos a todo el país",
  products: [
    {
      id: "bolso-tote-blanco",
      name: "Bolso  Alegi blanco",
      category: "bolsos",
      categoryLabel: "Bolsos",
      price: 45000,
      popular: 95,
      badge: "Top Ventas",
      ref: "BT-01",
      image: "img/bolso-tote-blanco.jpg",
      colors: ["Blanco perla", "Negro"],
      sizes: null,
      description: "Tote estructurado en tono hueso, con herrajes dorados suaves y espacio para el día a día. Ideal para oficina o un look de fin de semana.",
      highlights: ["Herrajes dorados", "Compartimento amplio", "Correa de hombro"]
    },
    {
      id: "bolso-baguette-negro",
      name: "Bolso beige con llavero incluido",
      category: "bolsos",
      categoryLabel: "Bolsos",
      price: 50000,
      popular: 92,
      badge: "Exclusivo",
      ref: "BG-02",
      image: "img/bolso-baguette-negro.jpg",
      colors: ["Negro", "Rosa"],
      sizes: null,
      description: "Baguette compacto de línea parisina. Cierre frontal y correa corta para llevar al hombro con outfits de noche o de ciudad.",
      highlights: ["Silueta baguette", "Broche dorado", "Tamaño compacto"]
    },
    {
      id: "tennis-blancos",
      name: "New Balance 9060 blancos",
      category: "tennis",
      categoryLabel: "Tennis",
      price: 155000,
      popular: 98,
      badge: "Top Ventas",
      ref: "TC-03",
      image: "img/tennis-blancos.jpg",
      colors: ["Blanco"],
      sizes: ["36", "37", "38", "39", "40"],
      description: "Tennis blancos de corte limpio y suela crema. Combinan con pantalón wide leg, vestido o jeans.",
      highlights: ["Corte clásico", "Plantilla cómoda", "Fácil de combinar"]
    },
    {
      id: "tennis-negros",
      name: "Nike Air Jordan 1 low",
      category: "tennis",
      categoryLabel: "Tennis",
      price: 155000,
      popular: 85,
      badge: "Nuevo",
      ref: "TN-04",
      image: "img/tennis-negros.jpg",
      colors: ["Negro"],
      sizes: ["36", "37", "38", "39", "40"],
      description: "Tennis negros con contraste blanco. Un básico urbano para looks casuales y de viaje.",
      highlights: ["Contraste blanco", "Uso diario", "Buen soporte"]
    },
    {
      id: "blusa-negra",
      name: "Enterizo Negro Malla",
      category: "ropa",
      categoryLabel: "Ropa",
      price: 75000,
      popular: 90,
      badge: "Top Ventas",
      ref: "BN-05",
      image: "img/blusa-negra.jpg",
      colors: ["Negro"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "Blusa negra de corte ajustado y manga larga. El básico que sostiene cualquier outfit Alegi.",
      highlights: ["Corte cómodo", "Fácil de planchar", "Combina con todo"]
    },
    {
      id: "pantalon-wide-leg",
      name: "Body Azul Cielo",
      category: "ropa",
      categoryLabel: "Ropa",
      price: 50000,
      compareAt: 119900,
      popular: 97,
      badge: "Exclusivo",
      ref: "ALG-8821",
      image: "img/pantalon-wide-leg.jpg",
      gallery: [
        "img/ficha-1.jpg",
        "img/ficha-2.jpg",
        "img/ficha-3.jpg",
        "img/ficha-4.jpg",
        "img/ficha-5.jpg"
      ],
      colors: ["Beige Arena", "Negro Noche", "Marfil", "Rosa palo"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "Pantalón de tiro alto con silueta wide leg. Tejido sastre que no transparenta y cae derecho. Queda igual de bien con tennis o con un bolso de noche.",
      highlights: [
        "Tiro alto con pretina reforzada",
        "Bolsillos laterales profundos",
        "Tela sastre: no transparenta"
      ]
    },
    {
      id: "set-dorado",
      name: "Set de accesorios dorados",
      category: "accesorios",
      categoryLabel: "Accesorios",
      price: 45900,
      popular: 88,
      badge: "Pocas unidades",
      ref: "AD-07",
      image: "img/set-dorado.jpg",
      colors: ["Dorado"],
      sizes: null,
      description: "Set de collar y aretes en tono oro champagne. Un toque fino para regalos o para elevar un look básico.",
      highlights: ["Baño dorado", "Piezas livianas", "Listo para regalar"]
    },
    {
      id: "mandarinSky",
      name: "Mandarin Sky",
      category: "perfumes",
      categoryLabel: "Perfumes",
      price: 110000,
      popular: 91,
      badge: "Nuevo",
      ref: "PF-08",
      image: "img/mandarinSky.jpg",
      colors: null,
      sizes: null,
      description: "Fragancia floral suave, con salida fresca y fondo cálido. Presentación de boutique, ideal para Amor y Amistad.",
      highlights: ["Aroma floral", "Duración media-alta", "Frasco de regalo"]
    },
    {
      id: "vestido-floral",
      name: "vestido Escote",
      category: "ropa",
      categoryLabel: "Ropa",
      price: 68000,
      popular: 86,
      badge: "Exclusivo",
      ref: "VF-09",
      image: "img/vestido-floral.jpg",
      colors: ["Floral arena"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "Vestido midi de inspiración floral, fresco y con caída suave. Perfecto para tarde, brunch o una salida especial.",
      highlights: ["Largo midi", "Estampado floral", "Tela liviana"]
    },
    {
      id: "mini-bolso-rosa",
      name: "Mini bolso acolchado rosa",
      category: "bolsos",
      categoryLabel: "Bolsos",
      price: 109900,
      popular: 94,
      badge: "Pocas unidades",
      ref: "MR-10",
      image: "img/mini-bolso-rosa.jpg",
      colors: ["Rosa", "Negro"],
      sizes: null,
      description: "Mini bag acolchado en rosa empolvado con cadena dorada. El tamaño justo para celular, llaves y un labial.",
      highlights: ["Acolchado", "Cadena dorada", "Formato mini"]
    },
    {
      id: "tennis-chunky",
      name: "Nike Air Force 1",
      category: "tennis",
      categoryLabel: "Tennis",
      price: 150000,
      popular: 89,
      badge: "Nuevo",
      ref: "TK-11",
      image: "img/tennis-chunky.jpg",
      colors: ["Crema"],
      sizes: ["36", "37", "38", "39", "40"],
      description: "Tennis chunky en crema con detalles dorados. Dan altura visual y cierran un look wide leg o un vestido midi.",
      highlights: ["Suela chunky", "Toques dorados", "Tendencia"]
    },
    {
      id: "set-perla",
      name: "Set aretes y collar perla",
      category: "accesorios",
      categoryLabel: "Accesorios",
      price: 39900,
      popular: 93,
      badge: "Top Ventas",
      ref: "AP-12",
      image: "img/set-perla.jpg",
      colors: ["Perla"],
      sizes: null,
      description: "Set delicado de perla y metal claro. Un clásico para regalos, eventos o el día a día.",
      highlights: ["Perla", "Piezas livianas", "Estuche de regalo"]
    },
    {
      id: "NikeDunkLow2",
      name: "Nike Dunk Low 2 Blancos",
      category: "tennis",
      categoryLabel: "Tennis",
      price: 155000,
      popular: 89,
      badge: "Nuevo",
      ref: "TK-11",
      image: "img/NikeDunkLow2.jpg",
      colors: ["Crema"],
      sizes: ["36", "37", "38", "39", "40"],
      description: "Tennis chunky en crema con detalles dorados. Dan altura visual y cierran un look wide leg o un vestido midi.",
      highlights: ["Suela chunky", "Toques dorados", "Tendencia"]
    },
    {
      id: "NikeSkateBlanco",
      name: "Nike Skate Blanco",
      category: "tennis",
      categoryLabel: "Tennis",
      price: 150000,
      popular: 89,
      badge: "Nuevo",
      ref: "TK-11",
      image: "img/NikeSkateBlancos.jpg",
      colors: ["Crema"],
      sizes: ["36", "37", "38", "39", "40"],
      description: "Tennis chunky en crema con detalles dorados. Dan altura visual y cierran un look wide leg o un vestido midi.",
      highlights: ["Suela chunky", "Toques dorados", "Tendencia"]
    },
    {
      id: "ZapatillasDeportivasAdidas",
      name: "Zapatillas Deportivas Adidas",
      category: "tennis",
      categoryLabel: "Tennis",
      price: 145000,
      popular: 89,
      badge: "Nuevo",
      ref: "TK-11",
      image: "img/zapatillasDeportivasAdidas.jpg",
      colors: ["Crema"],
      sizes: ["36", "37", "38", "39", "40"],
      description: "Tennis chunky en crema con detalles dorados. Dan altura visual y cierran un look wide leg o un vestido midi.",
      highlights: ["Suela chunky", "Toques dorados", "Tendencia"]
    },
  ]
};

window.ALEGI.waLink = function (text) {
  var msg = text || "Hola Alegi, quiero hacer un pedido";
  return "https://wa.me/" + window.ALEGI.phoneDigits + "?text=" + encodeURIComponent(msg);
};

window.ALEGI.formatPrice = function (n) {
  return "$ " + n.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".") + " COP";
};
